# Flight Delay and Cancellation Analysis
## Milestone 1 – Week 1: Data Foundation and Cleaning

### Internship: Infosys Springboard
### Dataset: Flight Delay & Cancellation (2019–2023)

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [5]:
df = pd.read_csv('../data/raw/flights_sample_3m.csv')
df.head()

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",1155,1151.0,-4.0,19.0,1210.0,1443.0,4.0,1501,1447.0,-14.0,0.0,NaN,0.0,186.0,176.0,153.0,1065.0,NaN,NaN,NaN,NaN,NaN
1,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",2120,2114.0,-6.0,9.0,2123.0,2232.0,38.0,2315,2310.0,-5.0,0.0,NaN,0.0,235.0,236.0,189.0,1399.0,NaN,NaN,NaN,NaN,NaN
2,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",954,1000.0,6.0,20.0,1020.0,1247.0,5.0,1252,1252.0,0.0,0.0,NaN,0.0,118.0,112.0,87.0,680.0,NaN,NaN,NaN,NaN,NaN
3,2023-03-06,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",1609,1608.0,-1.0,27.0,1635.0,1844.0,9.0,1829,1853.0,24.0,0.0,NaN,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0
4,2020-02-23,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",1840,1838.0,-2.0,15.0,1853.0,2026.0,14.0,2041,2040.0,-1.0,0.0,NaN,0.0,181.0,182.0,153.0,985.0,NaN,NaN,NaN,NaN,NaN

In [8]:
df.shape

(3000000, 32)

In [9]:
df.columns

Index(['FL_DATE', 'AIRLINE', 'AIRLINE_DOT', 'AIRLINE_CODE', 'DOT_CODE',
       'FL_NUMBER', 'ORIGIN', 'ORIGIN_CITY', 'DEST', 'DEST_CITY',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'DELAY_DUE_CARRIER',
       'DELAY_DUE_WEATHER', 'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY',
       'DELAY_DUE_LATE_AIRCRAFT'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 32 columns):
 #   Column                   Dtype
---  ------                   -----
 0   FL_DATE                  object
 1   AIRLINE                  object
 2   AIRLINE_DOT              object
 3   AIRLINE_CODE             object
 4   DOT_CODE                 int64
 5   FL_NUMBER                int64
 6   ORIGIN                   object
 7   ORIGIN_CITY              object
 8   DEST                     object
 9   DEST_CITY                object
 10  CRS_DEP_TIME             int64
 11  DEP_TIME                 float64
 12  DEP_DELAY                float64
 13  TAXI_OUT                 float64
 14  WHEELS_OFF               float64
 15  WHEELS_ON                float64
 16  TAXI_IN                  float64
 17  CRS_ARR_TIME             int64
 18  ARR_TIME                 float64
 19  ARR_DELAY                float64
 20  CANCELLED                float64
 21  CANCELLATION_CODE        object
 22  DIVERTED                 float64
 23  CRS_ELAPSED_TIME         float64
 24  ELAPSED_TIME             float64
 25  AIR_TIME                 float64
 26  DISTANCE                 float64
 27  DELAY_DUE_CARRIER        float64
 28  DELAY_DUE_WEATHER        float64
 29  DELAY_DUE_NAS            float64
 30  DELAY_DUE_SECURITY       float64
 31  DELAY_DUE_LATE_AIRCRAFT  float64
dtypes: float64(19), int64(4), object(9)
memory usage: 732.4+ MB

In [12]:
df.describe()

,DOT_CODE,FL_NUMBER,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT
count,3.000000e+06,3.000000e+06,3.000000e+06,2.922385e+06,2.922356e+06,2.921194e+06,2.921194e+06,2.920056e+06,2.920056e+06,3.000000e+06,2.920058e+06,2.913802e+06,3.000000e+06,3.000000e+06,2.999986e+06,2.913802e+06,2.913802e+06,3.000000e+06,533863.000000,533863.000000,533863.000000,533863.000000,533863.000000
mean,1.997629e+04,2.511536e+03,1.327062e+03,1.329776e+03,1.012333e+01,1.664305e+01,1.352361e+03,1.462500e+03,7.678982e+00,1.490561e+03,1.466511e+03,4.260858e+00,2.638000e-02,2.352000e-03,1.422758e+02,1.366205e+02,1.123108e+02,8.093616e+02,24.759086,3.985260,13.164728,0.145931,25.471282
std,3.772846e+02,1.747258e+03,4.858789e+02,4.993101e+02,4.925183e+01,9.192901e+00,5.008727e+02,5.272368e+02,6.269639e+00,5.115476e+02,5.318383e+02,5.117482e+01,1.602626e-01,4.844036e-02,7.155669e+01,7.167582e+01,6.975484e+01,5.878939e+02,71.771845,32.410796,33.161122,3.582053,55.766892
min,1.939300e+04,1.000000e+00,1.000000e+00,1.000000e+00,-9.000000e+01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-9.600000e+01,0.000000e+00,0.000000e+00,1.000000e+00,1.500000e+01,8.000000e+00,2.900000e+01,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.979000e+04,1.051000e+03,9.150000e+02,9.160000e+02,-6.000000e+00,1.100000e+01,9.310000e+02,1.049000e+03,4.000000e+00,1.107000e+03,1.053000e+03,-1.600000e+01,0.000000e+00,0.000000e+00,9.000000e+01,8.400000e+01,6.100000e+01,3.770000e+02,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.993000e+04,2.152000e+03,1.320000e+03,1.323000e+03,-2.000000e+00,1.400000e+01,1.336000e+03,1.501000e+03,6.000000e+00,1.516000e+03,1.505000e+03,-7.000000e+00,0.000000e+00,0.000000e+00,1.250000e+02,1.200000e+02,9.500000e+01,6.510000e+02,4.000000,0.000000,0.000000,0.000000,0.000000
75%,2.036800e+04,3.797000e+03,1.730000e+03,1.739000e+03,6.000000e+00,1.900000e+01,1.752000e+03,1.908000e+03,9.000000e+00,1.919000e+03,1.913000e+03,7.000000e+00,0.000000e+00,0.000000e+00,1.720000e+02,1.670000e+02,1.420000e+02,1.046000e+03,23.000000,0.000000,17.000000,0.000000,30.000000
max,2.045200e+04,9.562000e+03,2.359000e+03,2.400000e+03,2.966000e+03,1.840000e+02,2.400000e+03,2.400000e+03,2.490000e+02,2.400000e+03,2.400000e+03,2.934000e+03,1.000000e+00,1.000000e+00,7.050000e+02,7.390000e+02,6.920000e+02,5.812000e+03,2934.000000,1653.000000,1741.000000,1185.000000,2557.000000

In [13]:
df.isnull().sum().sort_values(ascending=False)
(df.isnull().sum() / len(df)) * 100

FL_DATE                     0.000000
AIRLINE                     0.000000
AIRLINE_DOT                 0.000000
AIRLINE_CODE                0.000000
DOT_CODE                    0.000000
FL_NUMBER                   0.000000
ORIGIN                      0.000000
ORIGIN_CITY                 0.000000
DEST                        0.000000
DEST_CITY                   0.000000
CRS_DEP_TIME                0.000000
DEP_TIME                    2.587167
DEP_DELAY                   2.588133
TAXI_OUT                    2.626867
WHEELS_OFF                  2.626867
WHEELS_ON                   2.664800
TAXI_IN                     2.664800
CRS_ARR_TIME                0.000000
ARR_TIME                    2.664733
ARR_DELAY                   2.873267
CANCELLED                   0.000000
CANCELLATION_CODE          97.362000
DIVERTED                    0.000000
CRS_ELAPSED_TIME            0.000467
ELAPSED_TIME                2.873267
AIR_TIME                    2.873267
DISTANCE                    0.000000
DELAY_DUE_CARRIER          82.204567
DELAY_DUE_WEATHER          82.204567
DELAY_DUE_NAS              82.204567
DELAY_DUE_SECURITY         82.204567
DELAY_DUE_LATE_AIRCRAFT    82.204567
dtype: float64

In [14]:
df.duplicated().sum()
df = df.drop_duplicates()

In [15]:
df.memory_usage(deep=True)

Index                            132
FL_DATE                    177000000
AIRLINE                    205780958
AIRLINE_DOT                217780958
AIRLINE_CODE               153000000
DOT_CODE                    24000000
FL_NUMBER                   24000000
ORIGIN                     156000000
ORIGIN_CITY                186344126
DEST                       156000000
DEST_CITY                  186346403
CRS_DEP_TIME                24000000
DEP_TIME                    24000000
DEP_DELAY                   24000000
TAXI_OUT                    24000000
WHEELS_OFF                  24000000
WHEELS_ON                   24000000
TAXI_IN                     24000000
CRS_ARR_TIME                24000000
ARR_TIME                    24000000
ARR_DELAY                   24000000
CANCELLED                   24000000
CANCELLATION_CODE           97424520
DIVERTED                    24000000
CRS_ELAPSED_TIME            24000000
ELAPSED_TIME                24000000
AIR_TIME                    24000000
DISTANCE                    24000000
DELAY_DUE_CARRIER           24000000
DELAY_DUE_WEATHER           24000000
DELAY_DUE_NAS               24000000
DELAY_DUE_SECURITY          24000000
DELAY_DUE_LATE_AIRCRAFT     24000000
dtype: int64

In [16]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].astype('category')

for col in df.select_dtypes(include=['int64']).columns:
    df[col] = pd.to_numeric(df[col], downcast='integer')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000000 entries, 0 to 2999999
Data columns (total 32 columns):
 #   Column                   Dtype
---  ------                   -----
 0   FL_DATE                  category
 1   AIRLINE                  category
 2   AIRLINE_DOT              category
 3   AIRLINE_CODE             category
 4   DOT_CODE                 int16
 5   FL_NUMBER                int16
 6   ORIGIN                   category
 7   ORIGIN_CITY              category
 8   DEST                     category
 9   DEST_CITY                category
 10  CRS_DEP_TIME             int16
 11  DEP_TIME                 float64
 12  DEP_DELAY                float64
 13  TAXI_OUT                 float64
 14  WHEELS_OFF               float64
 15  WHEELS_ON                float64
 16  TAXI_IN                  float64
 17  CRS_ARR_TIME             int16
 18  ARR_TIME                 float64
 19  ARR_DELAY                float64
 20  CANCELLED                float64
 21  CANCELLATION_CODE        category
 22  DIVERTED                 float64
 23  CRS_ELAPSED_TIME         float64
 24  ELAPSED_TIME             float64
 25  AIR_TIME                 float64
 26  DISTANCE                 float64
 27  DELAY_DUE_CARRIER        float64
 28  DELAY_DUE_WEATHER        float64
 29  DELAY_DUE_NAS            float64
 30  DELAY_DUE_SECURITY       float64
 31  DELAY_DUE_LATE_AIRCRAFT  float64
dtypes: category(9), float64(19), int16(4)
memory usage: 497.9 MB

In [18]:
df.to_csv('../data/processed/flights_sample_3m_week1_cleaned.csv', index=False)

In [19]:
df.columns

Index(['FL_DATE', 'AIRLINE', 'AIRLINE_DOT', 'AIRLINE_CODE', 'DOT_CODE',
       'FL_NUMBER', 'ORIGIN', 'ORIGIN_CITY', 'DEST', 'DEST_CITY',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'DELAY_DUE_CARRIER',
       'DELAY_DUE_WEATHER', 'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY',
       'DELAY_DUE_LATE_AIRCRAFT'],
      dtype='object')

In [22]:
df.isnull().sum().sort_values(ascending=False)

CANCELLATION_CODE          2920860
DELAY_DUE_LATE_AIRCRAFT    2466137
DELAY_DUE_SECURITY         2466137
DELAY_DUE_NAS              2466137
DELAY_DUE_WEATHER          2466137
DELAY_DUE_CARRIER          2466137
AIR_TIME                     86198
ELAPSED_TIME                 86198
ARR_DELAY                    86198
WHEELS_ON                    79944
TAXI_IN                      79944
ARR_TIME                     79942
TAXI_OUT                     78806
WHEELS_OFF                   78806
DEP_DELAY                    77644
DEP_TIME                     77615
CRS_ELAPSED_TIME                14
ORIGIN_CITY                      0
AIRLINE_DOT                      0
AIRLINE_CODE                     0
DOT_CODE                         0
FL_NUMBER                        0
DISTANCE                         0
ORIGIN                           0
DEST                             0
DIVERTED                         0
CANCELLED                        0
DEST_CITY                        0
CRS_ARR_TIME                     0
AIRLINE                          0
CRS_DEP_TIME                     0
FL_DATE                          0
dtype: int64

In [24]:
df['CANCELLATION_CODE'] = df['CANCELLATION_CODE'].cat.add_categories('Not Cancelled')
df['CANCELLATION_CODE'] = df['CANCELLATION_CODE'].fillna('Not Cancelled')

In [25]:
df['CANCELLATION_CODE'].isnull().sum()

np.int64(0)

In [26]:
delay_cols = [
    'DELAY_DUE_CARRIER',
    'DELAY_DUE_WEATHER',
    'DELAY_DUE_NAS',
    'DELAY_DUE_SECURITY',
    'DELAY_DUE_LATE_AIRCRAFT'
]

for col in delay_cols:
    df[col] = df[col].fillna(0)

In [27]:
df.loc[df['CANCELLED'] == 1, 'DEP_DELAY'] = 0
df.loc[df['CANCELLED'] == 1, 'ARR_DELAY'] = 0
df['DEP_DELAY'] = df['DEP_DELAY'].fillna(0)
df['ARR_DELAY'] = df['ARR_DELAY'].fillna(0)

In [28]:
df.isnull().sum().sort_values(ascending=False)

ELAPSED_TIME               86198
AIR_TIME                   86198
TAXI_IN                    79944
WHEELS_ON                  79944
ARR_TIME                   79942
WHEELS_OFF                 78806
TAXI_OUT                   78806
DEP_TIME                   77615
CRS_ELAPSED_TIME              14
DISTANCE                       0
DIVERTED                       0
DELAY_DUE_CARRIER              0
CANCELLATION_CODE              0
DELAY_DUE_WEATHER              0
DELAY_DUE_NAS                  0
DELAY_DUE_SECURITY             0
CANCELLED                      0
ARR_DELAY                      0
FL_DATE                        0
CRS_ARR_TIME                   0
AIRLINE                        0
DEP_DELAY                      0
CRS_DEP_TIME                   0
DEST_CITY                      0
DEST                           0
ORIGIN_CITY                    0
ORIGIN                         0
FL_NUMBER                      0
DOT_CODE                       0
AIRLINE_CODE                   0
AIRLINE_DOT                    0
DELAY_DUE_LATE_AIRCRAFT        0
dtype: int64

In [29]:
df['CRS_ELAPSED_TIME'] = df['CRS_ELAPSED_TIME'].fillna(df['CRS_ELAPSED_TIME'].median())

In [30]:
df['FL_DATE'] = pd.to_datetime(df['FL_DATE'])

In [31]:
df['Year'] = df['FL_DATE'].dt.year
df['Month'] = df['FL_DATE'].dt.month
df['DayOfWeek'] = df['FL_DATE'].dt.day_name()

In [32]:
df['DepHour'] = pd.to_datetime(df['DEP_TIME'], format='%H%M', errors='coerce').dt.hour

In [34]:
df['Route'] = df['ORIGIN'].astype(str) + "-" + df['DEST'].astype(str)

In [35]:
df['Route'] = df[['ORIGIN', 'DEST']].astype(str).agg('-'.join, axis=1)

In [36]:
df[['ORIGIN','DEST','Route']].head()

  ORIGIN DEST    Route
0    FLL  EWR  FLL-EWR
1    MSP  SEA  MSP-SEA
2    DEN  MSP  DEN-MSP
3    MSP  SFO  MSP-SFO
4    MCO  DFW  MCO-DFW

In [37]:
df = df[df['CANCELLED'] == 0]

In [38]:
df.isnull().sum()

FL_DATE                       0
AIRLINE                       0
AIRLINE_DOT                   0
AIRLINE_CODE                  0
DOT_CODE                      0
FL_NUMBER                     0
ORIGIN                        0
ORIGIN_CITY                   0
DEST                          0
DEST_CITY                     0
CRS_DEP_TIME                  0
DEP_TIME                      0
DEP_DELAY                     0
TAXI_OUT                      0
WHEELS_OFF                    0
WHEELS_ON                   804
TAXI_IN                     804
CRS_ARR_TIME                  0
ARR_TIME                    802
ARR_DELAY                     0
CANCELLED                     0
CANCELLATION_CODE             0
DIVERTED                      0
CRS_ELAPSED_TIME              0
ELAPSED_TIME               7058
AIR_TIME                   7058
DISTANCE                      0
DELAY_DUE_CARRIER             0
DELAY_DUE_WEATHER             0
DELAY_DUE_NAS                 0
DELAY_DUE_SECURITY            0
DELAY_DUE_LATE_AIRCRAFT       0
Year                          0
Month                         0
DayOfWeek                     0
DepHour                    2620
Route                         0
dtype: int64

In [39]:
df = df.dropna(subset=[
    'DEP_TIME',
    'ARR_TIME',
    'AIR_TIME',
    'DEP_DELAY',
    'ARR_DELAY'
])

In [40]:
df['FL_DATE'] = pd.to_datetime(df['FL_DATE'])

In [41]:
df['DELAY_STATUS'] = df['ARR_DELAY'].apply(
    lambda x: 1 if x > 15 else 0
)

In [42]:
df['TOTAL_DELAY'] = (
    df['DELAY_DUE_CARRIER'] +
    df['DELAY_DUE_WEATHER'] +
    df['DELAY_DUE_NAS'] +
    df['DELAY_DUE_SECURITY'] +
    df['DELAY_DUE_LATE_AIRCRAFT']
)

In [43]:
df['DISTANCE_CATEGORY'] = pd.cut(
    df['DISTANCE'],
    bins=[0, 500, 1500, 3000, 10000],
    labels=['Short', 'Medium', 'Long', 'Very Long']
)

In [44]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['AIRLINE_ENC'] = le.fit_transform(df['AIRLINE'])
df['ORIGIN_ENC'] = le.fit_transform(df['ORIGIN'])
df['DEST_ENC'] = le.fit_transform(df['DEST'])

In [45]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 2913802 entries, 0 to 2999999
Data columns (total 43 columns):
 #   Column                   Dtype
---  ------                   -----
 0   FL_DATE                  datetime64[ns]
 1   AIRLINE                  category
 2   AIRLINE_DOT              category
 3   AIRLINE_CODE             category
 4   DOT_CODE                 int16
 5   FL_NUMBER                int16
 6   ORIGIN                   category
 7   ORIGIN_CITY              category
 8   DEST                     category
 9   DEST_CITY                category
 10  CRS_DEP_TIME             int16
 11  DEP_TIME                 float64
 12  DEP_DELAY                float64
 13  TAXI_OUT                 float64
 14  WHEELS_OFF               float64
 15  WHEELS_ON                float64
 16  TAXI_IN                  float64
 17  CRS_ARR_TIME             int16
 18  ARR_TIME                 float64
 19  ARR_DELAY                float64
 20  CANCELLED                float64
 21  CANCELLATION_CODE        category
 22  DIVERTED                 float64
 23  CRS_ELAPSED_TIME         float64
 24  ELAPSED_TIME             float64
 25  AIR_TIME                 float64
 26  DISTANCE                 float64
 27  DELAY_DUE_CARRIER        float64
 28  DELAY_DUE_WEATHER        float64
 29  DELAY_DUE_NAS            float64
 30  DELAY_DUE_SECURITY       float64
 31  DELAY_DUE_LATE_AIRCRAFT  float64
 32  Year                     int32
 33  Month                    int32
 34  DayOfWeek                object
 35  DepHour                  float64
 36  Route                    object
 37  DELAY_STATUS             int64
 38  TOTAL_DELAY              float64
 39  DISTANCE_CATEGORY        category
 40  AIRLINE_ENC              int64
 41  ORIGIN_ENC               int64
 42  DEST_ENC                 int64
dtypes: category(9), datetime64[ns](1), float64(21), int16(4), int32(2), int64(4), object(2)
memory usage: 725.3+ MB

,FL_DATE,AIRLINE,AIRLINE_DOT,AIRLINE_CODE,DOT_CODE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ELAPSED_TIME,AIR_TIME,DISTANCE,DELAY_DUE_CARRIER,DELAY_DUE_WEATHER,DELAY_DUE_NAS,DELAY_DUE_SECURITY,DELAY_DUE_LATE_AIRCRAFT,Year,Month,DayOfWeek,DepHour,Route,DELAY_STATUS,TOTAL_DELAY,DISTANCE_CATEGORY,AIRLINE_ENC,ORIGIN_ENC,DEST_ENC
0,2019-01-09,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,1562,FLL,"Fort Lauderdale, FL",EWR,"Newark, NJ",1155,1151.0,-4.0,19.0,1210.0,1443.0,4.0,1501,1447.0,-14.0,0.0,Not Cancelled,0.0,186.0,176.0,153.0,1065.0,0.0,0.0,0.0,0.0,0.0,2019,1,Wednesday,11.0,FLL-EWR,0,0.0,Medium,17,131,123
1,2022-11-19,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,1149,MSP,"Minneapolis, MN",SEA,"Seattle, WA",2120,2114.0,-6.0,9.0,2123.0,2232.0,38.0,2315,2310.0,-5.0,0.0,Not Cancelled,0.0,235.0,236.0,189.0,1399.0,0.0,0.0,0.0,0.0,0.0,2022,11,Saturday,21.0,MSP-SEA,0,0.0,Medium,3,247,323
2,2022-07-22,United Air Lines Inc.,United Air Lines Inc.: UA,UA,19977,459,DEN,"Denver, CO",MSP,"Minneapolis, MN",954,1000.0,6.0,20.0,1020.0,1247.0,5.0,1252,1252.0,0.0,0.0,Not Cancelled,0.0,118.0,112.0,87.0,680.0,0.0,0.0,0.0,0.0,0.0,2022,7,Friday,10.0,DEN-MSP,0,0.0,Medium,17,99,247
3,2023-03-06,Delta Air Lines Inc.,Delta Air Lines Inc.: DL,DL,19790,2295,MSP,"Minneapolis, MN",SFO,"San Francisco, CA",1609,1608.0,-1.0,27.0,1635.0,1844.0,9.0,1829,1853.0,24.0,0.0,Not Cancelled,0.0,260.0,285.0,249.0,1589.0,0.0,0.0,24.0,0.0,0.0,2023,3,Monday,16.0,MSP-SFO,1,24.0,Long,3,247,325
4,2020-02-23,Spirit Air Lines,Spirit Air Lines: NK,NK,20416,407,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",1840,1838.0,-2.0,15.0,1853.0,2026.0,14.0,2041,2040.0,-1.0,0.0,Not Cancelled,0.0,181.0,182.0,153.0,985.0,0.0,0.0,0.0,0.0,0.0,2020,2,Sunday,18.0,MCO-DFW,0,0.0,Medium,16,223,100

In [49]:
df.to_csv("flight_data_preprocessed.csv", index=False)

In [50]:
df.to_csv("flight_data_preprocessed.csv", index=False)

In [51]:
import os
os.listdir()

['.ipynb_checkpoints',
 'flight_data_preprocessed.csv',
 'Milestone1_DataFoundation.ipynb.ipynb']

In [52]:
os.getcwd()

'C:\\Users\\admin\\flight-delay-project\\notebooks'

In [53]:
df.to_csv(r"C:\Users\admin\Desktop\flight_data_preprocessed.csv", index=False)